### ISSUE TITLE
Configuration Actions

### ISSUE THREAD

**Issue by Actimel** [keboola/developer-portal-ui#527] opened 2018-09-04 08:19 UTC
Field with Actions of component it is a bit confusing. It looks like searchable select element, but you want to type name of action there.

When you write a name of action and click somewhere outside this input the text you wrote is immediately gone.

<img width="649" alt="snimek obrazovky 2018-09-04 v 10 14 49" src="https://user-images.githubusercontent.com/4041679/45019100-bfa2cd00-b02b-11e8-9952-465085b686ef.png">

**Comment by ujovlado** [comment] 2018-09-04 08:48
Unfortunately `searchable` cannot be turned off. :) ... another workaround can be `openOnClick=false`, but that is only partial solution (still opens on double click).

We should upgrade react-select to latest version (v2) and then try again.

**Comment by Actimel** [comment] 2018-09-04 08:53
Would be great if we wont remove the text you write into it, at least.

**Comment by ujovlado** [comment] 2018-09-04 08:54
Depends. That component "prompts you" to create option and you clicked away :)

**Comment by ujovlado** [comment] 2018-10-04 08:27
I checked react-select docs few times. I think I'll close it here as "by design" ... since this is super minor and solving it would require more time and value which it adds is probably very small.

We can reopen it if someone else bumps to similar problem.

**Closed by ujovlado** 2018-10-04 08:27 UTC
Labels: area: ui/ux, module: admin, module: home, type: enhancement
