### ISSUE TITLE
Homepage: First steps diagram

### ISSUE THREAD

**Issue by kacurez** [keboola/developer-portal-ui#130] opened 2017-07-26 15:17 UTC
grafika popisu zaciatocnych krokov:
momentalne tam je len ako obycajny list
- Create Account
- Study Resources & API
- Create & Upload App
- Make your App Public

Jackov navrh:
![image](https://user-images.githubusercontent.com/1412120/28628748-cd2eba0a-7225-11e7-827f-1450e2fb1a40.png)

krok `Create Account` je klikatelny

**Comment by ujovlado** [comment] 2017-08-07 20:34
Duplicate of #11

**Closed** 2017-08-16 17:59 UTC
Labels: area:js, module:open, type:enhancement
